// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

import 'config/FirebaseConfig.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static final FirebaseOptions web = FirebaseOptions(
    apiKey: FirebaseConfig.apiKey_web,
    appId: '1:35717732646:web:a7603f04bc5ef4156789e7',
    messagingSenderId: '35717732646',
    projectId: 'smartcv-8fb89',
    authDomain: 'smartcv-8fb89.firebaseapp.com',
    storageBucket: 'smartcv-8fb89.firebasestorage.app',
  );

  static final FirebaseOptions android = FirebaseOptions(
    apiKey: FirebaseConfig.apiKey_android,
    appId: '1:35717732646:android:60c28157882eb3bc6789e7',
    messagingSenderId: '35717732646',
    projectId: 'smartcv-8fb89',
    storageBucket: 'smartcv-8fb89.firebasestorage.app',
  );

  static final FirebaseOptions ios = FirebaseOptions(
    apiKey: FirebaseConfig.apiKey_ios,
    appId: '1:35717732646:ios:0f255e5501626e836789e7',
    messagingSenderId: '35717732646',
    projectId: 'smartcv-8fb89',
    storageBucket: 'smartcv-8fb89.firebasestorage.app',
    iosBundleId: 'com.example.smartcvApp',
  );
}
